spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.boot: INFO
    ua.ithillel.javapro.controller: DEBUG
    ua.ithillel.javapro: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_DB_URL}
    username: ${POSTGRE_DB_USER}
    password: ${POSTGRE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
