spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&serverTimezone=UTC
    username: root
    password: sqldimachep5129
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.boot: INFO
    ua.ithillel.javapro.controller: DEBUG
    ua.ithillel.javapro: DEBUG
