name: Hillel Git JavaPro
on:
  - push

jobs:
  test:
    name: Unit tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '22.0.1'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode test